run:
  timeout: 5m

issues:
  exclude-dirs:
    - internal/ui
    - cmd/ui_client
  exclude-files:
    - ".*\\.pb\\.go$"  # Exclude generated protobuf files

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused
  disable:
    - typecheck  # Disable typecheck for UI packages that need display env