# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from experience.v1 import experience_pb2 as experience_dot_v1_dot_experience__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in experience/v1/experience_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExperienceServiceStub(object):
    """ExperienceService provides APIs for experience collection and consumption
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamExperiences = channel.unary_stream(
                '/generals.experience.v1.ExperienceService/StreamExperiences',
                request_serializer=experience_dot_v1_dot_experience__pb2.StreamExperiencesRequest.SerializeToString,
                response_deserializer=experience_dot_v1_dot_experience__pb2.Experience.FromString,
                _registered_method=True)
        self.SubmitExperiences = channel.unary_unary(
                '/generals.experience.v1.ExperienceService/SubmitExperiences',
                request_serializer=experience_dot_v1_dot_experience__pb2.SubmitExperiencesRequest.SerializeToString,
                response_deserializer=experience_dot_v1_dot_experience__pb2.SubmitExperiencesResponse.FromString,
                _registered_method=True)
        self.GetExperienceStats = channel.unary_unary(
                '/generals.experience.v1.ExperienceService/GetExperienceStats',
                request_serializer=experience_dot_v1_dot_experience__pb2.GetExperienceStatsRequest.SerializeToString,
                response_deserializer=experience_dot_v1_dot_experience__pb2.GetExperienceStatsResponse.FromString,
                _registered_method=True)


class ExperienceServiceServicer(object):
    """ExperienceService provides APIs for experience collection and consumption
    """

    def StreamExperiences(self, request, context):
        """StreamExperiences streams collected experiences to a trainer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitExperiences(self, request, context):
        """SubmitExperiences allows batch submission of experiences (for distributed collection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperienceStats(self, request, context):
        """GetExperienceStats returns statistics about collected experiences
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExperienceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamExperiences': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExperiences,
                    request_deserializer=experience_dot_v1_dot_experience__pb2.StreamExperiencesRequest.FromString,
                    response_serializer=experience_dot_v1_dot_experience__pb2.Experience.SerializeToString,
            ),
            'SubmitExperiences': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitExperiences,
                    request_deserializer=experience_dot_v1_dot_experience__pb2.SubmitExperiencesRequest.FromString,
                    response_serializer=experience_dot_v1_dot_experience__pb2.SubmitExperiencesResponse.SerializeToString,
            ),
            'GetExperienceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperienceStats,
                    request_deserializer=experience_dot_v1_dot_experience__pb2.GetExperienceStatsRequest.FromString,
                    response_serializer=experience_dot_v1_dot_experience__pb2.GetExperienceStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generals.experience.v1.ExperienceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generals.experience.v1.ExperienceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExperienceService(object):
    """ExperienceService provides APIs for experience collection and consumption
    """

    @staticmethod
    def StreamExperiences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generals.experience.v1.ExperienceService/StreamExperiences',
            experience_dot_v1_dot_experience__pb2.StreamExperiencesRequest.SerializeToString,
            experience_dot_v1_dot_experience__pb2.Experience.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitExperiences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.experience.v1.ExperienceService/SubmitExperiences',
            experience_dot_v1_dot_experience__pb2.SubmitExperiencesRequest.SerializeToString,
            experience_dot_v1_dot_experience__pb2.SubmitExperiencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperienceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.experience.v1.ExperienceService/GetExperienceStats',
            experience_dot_v1_dot_experience__pb2.GetExperienceStatsRequest.SerializeToString,
            experience_dot_v1_dot_experience__pb2.GetExperienceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
