# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\x12generals.common.v1\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05*~\n\x08TileType\x12\x19\n\x15TILE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10TILE_TYPE_NORMAL\x10\x01\x12\x15\n\x11TILE_TYPE_GENERAL\x10\x02\x12\x12\n\x0eTILE_TYPE_CITY\x10\x03\x12\x16\n\x12TILE_TYPE_MOUNTAIN\x10\x04*\x85\x01\n\x0cPlayerStatus\x12\x1d\n\x19PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14PLAYER_STATUS_ACTIVE\x10\x01\x12\x1c\n\x18PLAYER_STATUS_ELIMINATED\x10\x02\x12\x1e\n\x1aPLAYER_STATUS_DISCONNECTED\x10\x03*?\n\nActionType\x12\x1b\n\x17\x41\x43TION_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41\x43TION_TYPE_MOVE\x10\x01*\x92\x03\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\"\n\x1e\x45RROR_CODE_INVALID_COORDINATES\x10\x01\x12\x1b\n\x17\x45RROR_CODE_NOT_ADJACENT\x10\x02\x12\x18\n\x14\x45RROR_CODE_NOT_OWNED\x10\x03\x12 \n\x1c\x45RROR_CODE_INSUFFICIENT_ARMY\x10\x04\x12\x18\n\x14\x45RROR_CODE_GAME_OVER\x10\x05\x12\x1d\n\x19\x45RROR_CODE_INVALID_PLAYER\x10\x06\x12\x1b\n\x17\x45RROR_CODE_MOVE_TO_SELF\x10\x07\x12!\n\x1d\x45RROR_CODE_TARGET_IS_MOUNTAIN\x10\x08\x12\x1b\n\x17\x45RROR_CODE_INVALID_TURN\x10\t\x12\x1d\n\x19\x45RROR_CODE_GAME_NOT_FOUND\x10\n\x12\x18\n\x14\x45RROR_CODE_GAME_FULL\x10\x0b\x12\x1d\n\x19\x45RROR_CODE_ALREADY_JOINED\x10\x0c*\x94\x01\n\nGameStatus\x12\x1b\n\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13GAME_STATUS_WAITING\x10\x01\x12\x1b\n\x17GAME_STATUS_IN_PROGRESS\x10\x02\x12\x18\n\x14GAME_STATUS_FINISHED\x10\x03\x12\x19\n\x15GAME_STATUS_CANCELLED\x10\x04\x42VZTgithub.com/mitchelldurbincs/GeneralsReinforcementLearning/pkg/api/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZTgithub.com/mitchelldurbincs/GeneralsReinforcementLearning/pkg/api/common/v1;commonv1'
  _globals['_TILETYPE']._serialized_start=82
  _globals['_TILETYPE']._serialized_end=208
  _globals['_PLAYERSTATUS']._serialized_start=211
  _globals['_PLAYERSTATUS']._serialized_end=344
  _globals['_ACTIONTYPE']._serialized_start=346
  _globals['_ACTIONTYPE']._serialized_end=409
  _globals['_ERRORCODE']._serialized_start=412
  _globals['_ERRORCODE']._serialized_end=814
  _globals['_GAMESTATUS']._serialized_start=817
  _globals['_GAMESTATUS']._serialized_end=965
  _globals['_COORDINATE']._serialized_start=46
  _globals['_COORDINATE']._serialized_end=80
# @@protoc_insertion_point(module_scope)
