# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from game.v1 import game_pb2 as game_dot_v1_dot_game__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/v1/game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """GameService provides the gRPC API for the Generals.io game
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/generals.game.v1.GameService/CreateGame',
                request_serializer=game_dot_v1_dot_game__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=game_dot_v1_dot_game__pb2.CreateGameResponse.FromString,
                _registered_method=True)
        self.JoinGame = channel.unary_unary(
                '/generals.game.v1.GameService/JoinGame',
                request_serializer=game_dot_v1_dot_game__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=game_dot_v1_dot_game__pb2.JoinGameResponse.FromString,
                _registered_method=True)
        self.SubmitAction = channel.unary_unary(
                '/generals.game.v1.GameService/SubmitAction',
                request_serializer=game_dot_v1_dot_game__pb2.SubmitActionRequest.SerializeToString,
                response_deserializer=game_dot_v1_dot_game__pb2.SubmitActionResponse.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_unary(
                '/generals.game.v1.GameService/GetGameState',
                request_serializer=game_dot_v1_dot_game__pb2.GetGameStateRequest.SerializeToString,
                response_deserializer=game_dot_v1_dot_game__pb2.GetGameStateResponse.FromString,
                _registered_method=True)
        self.StreamGame = channel.unary_stream(
                '/generals.game.v1.GameService/StreamGame',
                request_serializer=game_dot_v1_dot_game__pb2.StreamGameRequest.SerializeToString,
                response_deserializer=game_dot_v1_dot_game__pb2.GameUpdate.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """GameService provides the gRPC API for the Generals.io game
    """

    def CreateGame(self, request, context):
        """CreateGame creates a new game instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """JoinGame allows a player to join an existing game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAction(self, request, context):
        """SubmitAction submits a player action (move) to the game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """GetGameState retrieves the current game state for a player (with fog of war)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGame(self, request, context):
        """StreamGame streams real-time game updates to connected players
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=game_dot_v1_dot_game__pb2.CreateGameRequest.FromString,
                    response_serializer=game_dot_v1_dot_game__pb2.CreateGameResponse.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=game_dot_v1_dot_game__pb2.JoinGameRequest.FromString,
                    response_serializer=game_dot_v1_dot_game__pb2.JoinGameResponse.SerializeToString,
            ),
            'SubmitAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAction,
                    request_deserializer=game_dot_v1_dot_game__pb2.SubmitActionRequest.FromString,
                    response_serializer=game_dot_v1_dot_game__pb2.SubmitActionResponse.SerializeToString,
            ),
            'GetGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=game_dot_v1_dot_game__pb2.GetGameStateRequest.FromString,
                    response_serializer=game_dot_v1_dot_game__pb2.GetGameStateResponse.SerializeToString,
            ),
            'StreamGame': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGame,
                    request_deserializer=game_dot_v1_dot_game__pb2.StreamGameRequest.FromString,
                    response_serializer=game_dot_v1_dot_game__pb2.GameUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generals.game.v1.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generals.game.v1.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """GameService provides the gRPC API for the Generals.io game
    """

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.game.v1.GameService/CreateGame',
            game_dot_v1_dot_game__pb2.CreateGameRequest.SerializeToString,
            game_dot_v1_dot_game__pb2.CreateGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.game.v1.GameService/JoinGame',
            game_dot_v1_dot_game__pb2.JoinGameRequest.SerializeToString,
            game_dot_v1_dot_game__pb2.JoinGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.game.v1.GameService/SubmitAction',
            game_dot_v1_dot_game__pb2.SubmitActionRequest.SerializeToString,
            game_dot_v1_dot_game__pb2.SubmitActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generals.game.v1.GameService/GetGameState',
            game_dot_v1_dot_game__pb2.GetGameStateRequest.SerializeToString,
            game_dot_v1_dot_game__pb2.GetGameStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generals.game.v1.GameService/StreamGame',
            game_dot_v1_dot_game__pb2.StreamGameRequest.SerializeToString,
            game_dot_v1_dot_game__pb2.GameUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
